# Generated by Django 4.2.17 on 2025-01-14 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_record_delete_blocklistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='blockchain_record',
        ),
        migrations.RemoveField(
            model_name='record',
            name='record_location',
        ),
    ]
