# Generated by Django 4.2.17 on 2025-01-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_record_blockchain_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='pdf_file_url',
            field=models.URLField(blank=True, null=True, verbose_name='PDF File URL'),
        ),
        migrations.AddField(
            model_name='record',
            name='return_receipt_file_url',
            field=models.URLField(blank=True, null=True, verbose_name='Return Receipt File URL'),
        ),
        migrations.AddField(
            model_name='record',
            name='tracking_mail_receipt_url',
            field=models.URLField(blank=True, null=True, verbose_name='Tracking Mail Receipt URL'),
        ),
    ]
