# Generated by Django 4.2.17 on 2025-01-14 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_record_pdf_file_url_record_return_receipt_file_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='pdf_file_url',
        ),
        migrations.RemoveField(
            model_name='record',
            name='return_receipt_file_url',
        ),
        migrations.RemoveField(
            model_name='record',
            name='tracking_mail_receipt_url',
        ),
    ]
