# Generated by Django 4.2.17 on 2025-01-14 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_record_pdf_file_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='pdf_file',
            new_name='pdf_file_aws',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='return_receipt_file',
            new_name='return_receipt_file_aws',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='tracking_mail_receipt',
            new_name='tracking_mail_receipt_aws_aws',
        ),
    ]
