# Generated by Django 4.2.17 on 2025-01-14 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_pdf_file_record_pdf_file_aws_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='tracking_mail_receipt_aws_aws',
            new_name='tracking_mail_receipt_aws',
        ),
    ]
