# Generated by Django 4.2.17 on 2025-01-14 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_record_pdf_file_url_record_return_receipt_file_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='hash',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, verbose_name='SHA256'),
        ),
        migrations.AlterField(
            model_name='record',
            name='pdf_file_url',
            field=models.URLField(blank=True, editable=False, null=True, verbose_name='PDF File URL'),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_type',
            field=models.CharField(choices=[('cafv', 'Conditional-Acceptance-for-Value'), ('ipn', 'International-Promissory-Note'), ('boe', 'International-Bill-of-Exchange'), ('noticeBreach', 'Notice-of-Breach'), ('noticeCure', 'Notice-of-Cure'), ('noticeDefault', 'Notice-of-Default'), ('tort', 'Tort-Claim'), ('noticeDemand', 'Notice-of-Demand'), ('noticeDispute', 'Notice-of-Dispute'), ('noticeFraud', 'Notice-of-Fraud'), ('executor', 'Executor-Letter'), ('crn', 'Copyright-Notice')], default='default', max_length=20, verbose_name='Record Type'),
        ),
        migrations.AlterField(
            model_name='record',
            name='return_receipt_file_url',
            field=models.URLField(blank=True, editable=False, null=True, verbose_name='Return Receipt File URL'),
        ),
        migrations.AlterField(
            model_name='record',
            name='tracking_mail_receipt_url',
            field=models.URLField(blank=True, editable=False, null=True, verbose_name='Tracking Mail Receipt URL'),
        ),
    ]
