# Generated by Django 4.2.17 on 2025-01-14 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_record_hash_alter_record_pdf_file_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='pdf_file_url',
        ),
        migrations.RemoveField(
            model_name='record',
            name='return_receipt_file_url',
        ),
        migrations.RemoveField(
            model_name='record',
            name='tracking_mail_receipt_url',
        ),
        migrations.AlterField(
            model_name='record',
            name='tracking_type',
            field=models.CharField(blank=True, choices=[('certifiedmail_usps', 'Certified-Mail-USPS'), ('registeredmail_usps', 'Registered-Mail-USPS')], max_length=20, null=True, verbose_name='Tracking Type'),
        ),
    ]
