# Generated by Django 4.2.17 on 2025-01-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_record_pdf_file_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='uuid',
            field=models.CharField(default='', editable=False, max_length=36, unique=True, verbose_name='UUID'),
        ),
    ]
