# Generated by Django 4.2.17 on 2025-01-15 18:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_record_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
    ]
