# Generated by Django 4.2.17 on 2025-01-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_record_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_type',
            field=models.CharField(choices=[('cafv', 'Conditional-Acceptance-for-Value'), ('ipn', 'International-Promissory-Note'), ('boe', 'International-Bill-of-Exchange'), ('noticeBreach', 'Notice-of-Breach'), ('noticeCure', 'Notice-of-Cure'), ('noticeDefault', 'Notice-of-Default'), ('tort', 'Tort-Claim'), ('noticeDemand', 'Notice-of-Demand'), ('noticeDispute', 'Notice-of-Dispute'), ('noticeFraud', 'Notice-of-Fraud'), ('executor', 'Executor-Letter'), ('crn', 'Copyright-Notice'), ('noticeLien', 'Notice-of-Lien')], default='default', max_length=20, verbose_name='Record Type'),
        ),
    ]
