# Generated by Django 4.2.17 on 2025-01-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_record_record_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='access_logs',
            field=models.JSONField(default=list, verbose_name='Access Logs'),
        ),
    ]
