# Generated by Django 4.2.17 on 2025-02-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_documenttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='file_path',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
